import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: "GoGreen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="text-inter">
          <Navbar />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
